import Flutter
import Foundation
import Darwin  // pipe, read, write, close

// WasmSandboxHandler — iOS implementation of the ai.flutterclaw/sandbox MethodChannel.
//
// Architecture:
//   WAMR interpreter (Apache 2.0)
//     └─ TinyEMU-c2w (MIT)  — RISC-V64 CPU emulator compiled to Wasm
//          └─ Linux 6.1 kernel (custom, CONFIG_RISCV_SBI_V01=y)
//               └─ Alpine 3.21 userspace (python3, pip, git, curl, wget, jq, bash, file)
//
// Limitations vs Android:
//   - No internet in guest VM (WAMR networking WIP) → apk add online fails
//   - Packages fixed at image build time (pre-installed: python3, pip, git, curl, wget, jq, bash, file)
//   - ~10–100× slower than Android (RISC-V emulation on ARM64 hardware)
//   - riscv64 architecture (`uname -m` → riscv64)
//   - Single-core CPU (no SMP)
//
// WAMR integration:
//   WAMR is integrated via its C API through a bridging header (Runner-Bridging-Header.h).
//   The xcframework lives at ios/WAMR/wamr.xcframework.
//   sandbox_exec calls wasm_runtime_init(), loads the Wasm module, sets --dir for file
//   sharing, and communicates with TinyEMU via the virtio serial console (stdin/stdout
//   of the Wasm instance).

// MARK: - Persistent VM session (keeps TinyEMU alive between exec calls)
//
// Architecture:
//   First sandbox_exec boots TinyEMU (15-60s cold start).
//   Subsequent calls write commands directly to stdin and read stdout —
//   the kernel boot penalty is paid only once per app lifecycle.
//
// Protocol:
//   Boot marker: we write `echo "__WAMR_READY__"\n` to stdin before the VM
//   is even running; it gets buffered in the pipe and executed once ash starts.
//   We wait for `__WAMR_READY__` in stdout to confirm the VM is ready.
//
//   Per command: write `cd <dir>; <cmd>; echo "__WAMR_EXIT__$?"\n`,
//   then read stdout until the exit sentinel is found.
//   The tty echo and prompt lines are stripped by the existing noise filter.
//
// Thread safety: only one command at a time (enforced by sessionLock).
private final class WasmVMSession {
    // Pipe write-end for feeding commands into the VM
    let stdinWrite:    Int32
    // Pipe read-ends for consuming VM output
    let stdoutRead:    Int32
    let stderrRead:    Int32
    // Internal write-ends kept open so the drain threads don't see EOF prematurely
    let stdoutWriteInternal: Int32
    let stderrWriteInternal: Int32
    // Internal read-end of stdin (owned by WAMR)
    let stdinReadInternal: Int32

    // Rolling stdout accumulator: may contain data from previous reads
    var stdoutBuf = ""

    // Flag set when `__WAMR_READY__` has been seen in stdout
    var isReady = false

    // Set to true by the background VM thread when wasm_application_execute_main returns
    var vmExited = false

    init(stdinFds: (Int32, Int32),
         stdoutFds: (Int32, Int32),
         stderrFds: (Int32, Int32)) {
        stdinReadInternal  = stdinFds.0
        stdinWrite         = stdinFds.1
        stdoutRead         = stdoutFds.0
        stdoutWriteInternal = stdoutFds.1
        stderrRead         = stderrFds.0
        stderrWriteInternal = stderrFds.1
    }

    // Tear down all resources. Call from the session lock.
    func teardown() {
        for fd in [stdinReadInternal, stdinWrite,
                   stdoutRead, stdoutWriteInternal,
                   stderrRead, stderrWriteInternal] {
            if fd >= 0 { close(fd) }
        }
    }
}

class WasmSandboxHandler {

    // URL and SHA256 of the pre-built Wasm artefact.
    // Generated by scripts/ios-sandbox/build.sh or the build-ios-sandbox CI workflow.
    // Update both when publishing a new image version via GitHub release.
    static let wasmDownloadURL = "https://github.com/flutterclaw/flutterclaw/releases/download/ios-sandbox%2Fv3.21.0-1/alpine-ios-sandbox.initialized.wasm"
    static let wasmSHA256 = "8bf66d9b7702ae97bd60f97637b305ca1791a77168fe851b1af8bc2e28bb2ff8"
    static let wasmVersion = "3.21.0-1"

    // wasm_runtime_init must be called exactly once per process lifetime.
    private static var runtimeInitialised = false

    // Persistent VM session — nil until first sandbox_exec.
    private var vmSession: WasmVMSession?
    private let sessionLock = NSLock()

    private let channel: FlutterMethodChannel

    init(messenger: FlutterBinaryMessenger) {
        channel = FlutterMethodChannel(
            name: "ai.flutterclaw/sandbox",
            binaryMessenger: messenger
        )
        channel.setMethodCallHandler { [weak self] call, result in
            self?.handleMethodCall(call, result: result)
        }
    }

    private func handleMethodCall(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        switch call.method {
        case "sandbox_status":
            handleStatus(result: result)
        case "sandbox_setup":
            handleSetup(result: result)
        case "sandbox_exec":
            handleExec(call: call, result: result)
        default:
            result(FlutterMethodNotImplemented)
        }
    }

    // MARK: - sandbox_status

    private func handleStatus(result: @escaping FlutterResult) {
        let wasmURL = wasmFileURL()
        let wasmReady = FileManager.default.fileExists(atPath: wasmURL.path)
        let sharedPath = sharedDirectoryURL().path
        let sessionActive = sessionLock.withLock { vmSession?.isReady == true }

        result([
            "ready": wasmReady,
            "platform": "ios",
            "emulator": "tinyemu-riscv64",
            "network": false,
            "wasm_version": Self.wasmVersion,
            "shared_path": sharedPath,
            "root_path": rootPersistenceDirectoryURL().path,
            "proot_available": false,
            "rootfs_available": wasmReady,
            "vm_session_active": sessionActive,
            "note": sessionActive
                ? "Alpine 3.21 (riscv64). VM running — next exec is instant."
                : wasmReady
                    ? "Alpine 3.21 (riscv64 emulated). No internet in VM. Pre-installed: python3, pip, git, curl, wget, jq, bash, file."
                    : "Call sandbox_setup to download the Alpine Wasm image (~100-120 MB).",
        ] as [String: Any])
    }

    // MARK: - sandbox_setup

    private func handleSetup(result: @escaping FlutterResult) {
        // Kill any live VM session before re-provisioning so the new Wasm file
        // is loaded on the next sandbox_exec call.
        sessionLock.withLock {
            vmSession?.teardown()
            vmSession = nil
        }
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            do {
                try self.provision()
                DispatchQueue.main.async {
                    result(["ready": true, "platform": "ios"])
                }
            } catch {
                DispatchQueue.main.async {
                    result(["error": true, "message": error.localizedDescription])
                }
            }
        }
    }

    // Idempotent: skips download if the Wasm file already exists with the
    // correct version marker. Creates the shared directory regardless.
    private func provision() throws {
        let fm = FileManager.default
        let sandboxDir = sandboxDirectoryURL()
        let sharedDir = sharedDirectoryURL()
        let wasmFile = wasmFileURL()
        let versionFile = sandboxDir.appendingPathComponent(".wasm_version")

        // Create sandbox, shared, and persistent root directories.
        try fm.createDirectory(at: sandboxDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: sharedDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: rootPersistenceDirectoryURL(), withIntermediateDirectories: true)

        // Check if existing Wasm matches current version.
        if fm.fileExists(atPath: wasmFile.path),
           let storedVersion = try? String(contentsOf: versionFile, encoding: .utf8),
           storedVersion.trimmingCharacters(in: .whitespacesAndNewlines) == Self.wasmVersion {
            return  // Already provisioned and up to date.
        }

        // Remove stale Wasm if present.
        if fm.fileExists(atPath: wasmFile.path) {
            try fm.removeItem(at: wasmFile)
        }

        // Download the Wasm artefact.
        guard let url = URL(string: Self.wasmDownloadURL) else {
            throw SandboxError.invalidURL
        }

        var downloadError: Error?
        var downloadedURL: URL?
        let semaphore = DispatchSemaphore(value: 0)

        let task = URLSession.shared.downloadTask(with: url) { tmpURL, response, error in
            defer { semaphore.signal() }
            if let error {
                downloadError = error
                return
            }
            guard let tmpURL,
                  let httpResponse = response as? HTTPURLResponse,
                  httpResponse.statusCode == 200 else {
                downloadError = SandboxError.downloadFailed(
                    (response as? HTTPURLResponse)?.statusCode ?? 0
                )
                return
            }
            downloadedURL = tmpURL
        }
        task.resume()
        semaphore.wait()

        if let error = downloadError { throw error }
        guard let src = downloadedURL else { throw SandboxError.downloadFailed(0) }

        try fm.moveItem(at: src, to: wasmFile)

        // Verify SHA256 if configured (skip when empty for dev convenience).
        if !Self.wasmSHA256.isEmpty {
            let data = try Data(contentsOf: wasmFile)
            let digest = sha256Hex(data)
            guard digest == Self.wasmSHA256 else {
                try? fm.removeItem(at: wasmFile)
                throw SandboxError.sha256Mismatch(expected: Self.wasmSHA256, got: digest)
            }
        }

        try Self.wasmVersion.write(to: versionFile, atomically: true, encoding: .utf8)
    }

    // MARK: - sandbox_exec

    private func handleExec(call: FlutterMethodCall, result: @escaping FlutterResult) {
        guard let args = call.arguments as? [String: Any],
              let command = args["command"] as? String, !command.isEmpty else {
            result(["error": true, "message": "command is required"])
            return
        }
        let timeoutMs = (args["timeout_ms"] as? Int) ?? 30_000
        let workingDir = (args["working_dir"] as? String) ?? "/root"

        let wasmFile = wasmFileURL()
        guard FileManager.default.fileExists(atPath: wasmFile.path) else {
            result(["error": true, "message": "Sandbox not provisioned. Call sandbox_setup first."])
            return
        }

        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            let execResult = self.runInVM(
                command: command,
                workingDir: workingDir,
                timeoutMs: timeoutMs
            )
            DispatchQueue.main.async { result(execResult) }
        }
    }

    // Runs a shell command inside TinyEMU via WAMR.
    //
    // Persistence:
    //   A WasmVMSession keeps the WAMR instance + pipes alive between calls.
    //   The first call boots the VM (15-60s cold start). Subsequent calls write
    //   commands to the existing stdin pipe — no reboot penalty.
    //
    // Exit code:
    //   The command is wrapped with a sentinel: `echo "__WAMR_EXIT__$?"`.
    //   The sentinel is stripped from stdout and the code is extracted.
    private func runInVM(command: String, workingDir: String, timeoutMs: Int) -> [String: Any] {
        let maxOutputBytes = 65_536

        #if WAMR_AVAILABLE
        return wamrExecPersistent(command: command,
                                  workingDir: workingDir,
                                  timeoutMs: timeoutMs,
                                  maxOutputBytes: maxOutputBytes)
        #else
        return [
            "error": true,
            "message": "WAMR xcframework not yet integrated. Run scripts/build-wamr-ios.sh then pod install.",
        ]
        #endif
    }

    #if WAMR_AVAILABLE

    // MARK: - Persistent VM execution

    /// Main entry point for persistent execution. Creates a session on first
    /// call (cold boot), then reuses it for subsequent commands.
    private func wamrExecPersistent(command: String,
                                    workingDir: String,
                                    timeoutMs: Int,
                                    maxOutputBytes: Int) -> [String: Any] {
        sessionLock.lock()
        // Teardown dead sessions (VM exited unexpectedly).
        if let s = vmSession, s.vmExited {
            s.teardown()
            vmSession = nil
        }

        if vmSession == nil {
            // Cold boot: create pipes, load module, start VM background thread.
            let bootResult = createSession()
            if let err = bootResult.error {
                sessionLock.unlock()
                return ["error": true, "message": err]
            }
        }
        let session = vmSession!
        sessionLock.unlock()

        // Wait for ready (blocks until kernel boot on first call, instant after).
        let bootDeadline = DispatchTime.now() + .seconds(120)
        if !session.isReady {
            if !waitForSentinel(session: session,
                                sentinel: "__WAMR_READY__",
                                deadline: bootDeadline) {
                sessionLock.withLock { vmSession?.teardown(); vmSession = nil }
                return ["error": true, "message": "VM boot timed out (>120s)."]
            }
            session.isReady = true
        }

        // Run the command.
        let sentinel = "__WAMR_EXIT__"
        let wrappedCmd =
            "cd \(shellEscape(workingDir)) 2>/dev/null || cd /root\n" +
            command + "\n" +
            "echo \"\(sentinel)$?\"\n"
        let cmdData = (wrappedCmd + "\n").data(using: .utf8)!
        cmdData.withUnsafeBytes { ptr in
            _ = write(session.stdinWrite, ptr.baseAddress!, cmdData.count)
        }

        let deadline = DispatchTime.now() + .milliseconds(timeoutMs)
        if !waitForSentinel(session: session, sentinel: sentinel, deadline: deadline) {
            // Timed out — kill session so next call gets a fresh VM.
            sessionLock.withLock { vmSession?.teardown(); vmSession = nil }
            return ["exit_code": -1, "stdout": "", "stderr": "Command timed out.", "timed_out": true]
        }

        // Extract output up to and including the sentinel from the buffer.
        let raw = session.stdoutBuf
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")

        // Find sentinel position and split buffer: keep output before sentinel,
        // leave any trailing data in the buffer for the next command.
        guard let range = raw.range(of: sentinel) else {
            return ["exit_code": 0, "stdout": stripTinyEMUNoise(raw), "timed_out": false]
        }

        var outputPart = String(raw[..<range.lowerBound])
        let afterSentinel = String(raw[range.upperBound...])

        // Extract exit code from the line immediately following the sentinel.
        let firstLine = afterSentinel.components(separatedBy: "\n").first ?? ""
        let exitCodeStr = firstLine.trimmingCharacters(in: .whitespacesAndNewlines)
        let exitCode = Int(exitCodeStr) ?? 0

        // Retain anything after the exit code digit(s) + newline for next command.
        let remaining: String
        if let nl = afterSentinel.firstIndex(of: "\n") {
            remaining = String(afterSentinel[afterSentinel.index(after: nl)...])
        } else {
            remaining = ""
        }
        session.stdoutBuf = remaining

        outputPart = stripTinyEMUNoise(outputPart)
        return [
            "exit_code": exitCode,
            "stdout": outputPart,
            "stderr": "",
            "timed_out": false,
        ]
    }

    // -----------------------------------------------------------------------
    // Session creation
    // -----------------------------------------------------------------------

    private struct CreateSessionResult {
        let error: String?
    }

    private func createSession() -> CreateSessionResult {
        guard let wasmBytes = try? Data(contentsOf: wasmFileURL()) else {
            return CreateSessionResult(error: "Failed to read Wasm file.")
        }

        let rootPath   = rootPersistenceDirectoryURL().path
        let sharedPath = sharedDirectoryURL().path
        let argv: [String] = ["/bin/sh"]
        let dirs: [String] = [rootPath, sharedPath]
        let envs: [String] = ["TERM=xterm-256color", "HOME=/root",
                               "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]

        var inPipe  = [Int32](repeating: 0, count: 2)
        var outPipe = [Int32](repeating: 0, count: 2)
        var errPipe = [Int32](repeating: 0, count: 2)
        pipe(&inPipe); pipe(&outPipe); pipe(&errPipe)

        // Set stdout read-end non-blocking so waitForSentinel can poll.
        let flags = fcntl(outPipe[0], F_GETFL, 0)
        fcntl(outPipe[0], F_SETFL, flags | O_NONBLOCK)

        // Write ready probe immediately — buffered in pipe until shell starts.
        let probe = "echo \"__WAMR_READY__\"\n"
        let probeData = probe.data(using: .utf8)!
        probeData.withUnsafeBytes { ptr in
            _ = write(inPipe[1], ptr.baseAddress!, probeData.count)
        }

        let session = WasmVMSession(
            stdinFds:  (inPipe[0],  inPipe[1]),
            stdoutFds: (outPipe[0], outPipe[1]),
            stderrFds: (errPipe[0], errPipe[1])
        )
        vmSession = session

        // Load + instantiate WAMR (done once per session).
        var loadError = ""
        var mutableWasm = wasmBytes
        mutableWasm.withUnsafeMutableBytes { (rawPtr: UnsafeMutableRawBufferPointer) in
            guard let base = rawPtr.baseAddress else { loadError = "Nil Wasm buffer"; return }

            if !Self.runtimeInitialised {
                _ = wasm_runtime_init()
                Self.runtimeInitialised = true
            }

            var errBuf = [CChar](repeating: 0, count: 256)
            guard let module = wasm_runtime_load(
                base.assumingMemoryBound(to: UInt8.self),
                UInt32(wasmBytes.count),
                &errBuf, UInt32(errBuf.count)
            ) else {
                loadError = String(cString: errBuf)
                return
            }

            var cArgv = argv.map { strdup($0) }
            var cDirs = dirs.map { strdup($0) }
            var cEnvs = envs.map { strdup($0) }
            defer {
                cArgv.forEach { free($0) }
                cDirs.forEach { free($0) }
                cEnvs.forEach { free($0) }
            }

            var constDirs = cDirs.map { UnsafePointer($0) }
            var constEnvs = cEnvs.map { UnsafePointer($0) }
            cArgv.withUnsafeMutableBufferPointer { ab in
            constDirs.withUnsafeMutableBufferPointer { db in
            constEnvs.withUnsafeMutableBufferPointer { eb in
                wasm_runtime_set_wasi_args_ex(
                    module,
                    db.baseAddress, UInt32(dirs.count),
                    nil, 0,
                    eb.baseAddress, UInt32(envs.count),
                    ab.baseAddress, Int32(argv.count),
                    Int64(inPipe[0]),   // stdin  read-end
                    Int64(outPipe[1]),  // stdout write-end
                    Int64(errPipe[1])   // stderr write-end
                )
            }}}

            guard let instance = wasm_runtime_instantiate(
                module,
                1024 * 1024,
                16 * 1024 * 1024,
                &errBuf, UInt32(errBuf.count)
            ) else {
                wasm_runtime_unload(module)
                loadError = String(cString: errBuf)
                return
            }

            // Run the VM on a permanent background thread.
            // wasm_application_execute_main blocks until the Wasm module exits
            // (i.e., the Linux VM shuts down). We signal session.vmExited so the
            // next sandbox_exec creates a fresh session.
            let capturedArgv = argv  // capture for thread safety
            DispatchQueue.global(qos: .userInitiated).async { [weak session] in
                _ = wasm_runtime_init_thread_env()
                defer { wasm_runtime_destroy_thread_env() }

                var threadArgv = capturedArgv.map { strdup($0) }
                defer { threadArgv.forEach { free($0) } }
                threadArgv.withUnsafeMutableBufferPointer { buf in
                    _ = wasm_application_execute_main(instance, Int32(capturedArgv.count), buf.baseAddress)
                }
                wasm_runtime_deinstantiate(instance)
                wasm_runtime_unload(module)
                session?.vmExited = true
            }
        }

        if !loadError.isEmpty {
            session.teardown()
            vmSession = nil
            return CreateSessionResult(error: "WAMR load error: \(loadError)")
        }
        return CreateSessionResult(error: nil)
    }

    // -----------------------------------------------------------------------
    // Sentinel-based stdout polling (non-blocking reads with timeout)
    // -----------------------------------------------------------------------

    /// Reads from session.stdoutRead (non-blocking) until `sentinel` appears
    /// in the accumulated buffer, or `deadline` is reached.
    /// Returns true if sentinel was found.
    private func waitForSentinel(session: WasmVMSession,
                                  sentinel: String,
                                  deadline: DispatchTime) -> Bool {
        var chunk = [UInt8](repeating: 0, count: 8192)
        while DispatchTime.now() < deadline {
            let n = read(session.stdoutRead, &chunk, chunk.count)
            if n > 0 {
                session.stdoutBuf += String(bytes: chunk[..<n], encoding: .utf8) ?? ""
                if session.stdoutBuf.contains(sentinel) { return true }
            } else {
                // EAGAIN — no data yet; sleep 20ms before next poll.
                usleep(20_000)
            }
            if session.vmExited { return false }
        }
        return false
    }

    #endif

    private func shellEscape(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    // MARK: - Paths

    func wasmFileURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("alpine-ios-sandbox.wasm")
    }

    func sharedDirectoryURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("shared")
    }

    // Persistent /root/ for the Alpine guest.
    // Mounted via WAMR --dir + container2wasm virtio-9p at the same absolute path
    // inside the VM, so files written to /root/ inside Alpine survive across calls.
    func rootPersistenceDirectoryURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("root")
    }

    func sandboxDirectoryURL() -> URL {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("sandbox")
    }
}

// MARK: - TinyEMU output post-processing

// Strip the UART echo preamble and ash shell-prompt lines from TinyEMU stdout.
//
// Raw TinyEMU stdout structure (serial console / tty echo):
//
//   [preamble] echo of all stdin chars (before shell is ready)
//   ~ # cmd1          ← ash prompt + command
//   output1           ← kept
//   /tmp # cmd2       ← ash prompt (workdir changed)
//   output2           ← kept
//   ...
//
// Prompt lines are identified by: starts with "~" or "/" and contains " # "
// with no space in the working-directory portion (e.g. "~ # " or "/tmp # ").
//
// Limitation: output lines that happen to match the prompt pattern (e.g. a
// line like "/bin # something") will be incorrectly stripped.  This is
// acceptable for typical command output.
private func stripTinyEMUNoise(_ raw: String) -> String {
    let lines = raw.components(separatedBy: "\n")
    var pastPreamble = false
    var result: [String] = []

    for line in lines {
        if isTinyEMUPromptLine(line) {
            pastPreamble = true
            // Skip prompt lines.
        } else if pastPreamble {
            result.append(line)
        }
        // Skip preamble lines (before first prompt).
    }
    return result.joined(separator: "\n")
}

// Returns true if `line` looks like an ash prompt: starts with "~" or "/"
// and contains " # " with no spaces before the " # ".
private func isTinyEMUPromptLine(_ line: String) -> Bool {
    guard line.hasPrefix("~") || line.hasPrefix("/") else { return false }
    guard let hashRange = line.range(of: " # ") else { return false }
    let workingDir = String(line[..<hashRange.lowerBound])
    return !workingDir.contains(" ")
}

// MARK: - SHA256

import CommonCrypto

private func sha256Hex(_ data: Data) -> String {
    var digest = [UInt8](repeating: 0, count: Int(CC_SHA256_DIGEST_LENGTH))
    data.withUnsafeBytes { CC_SHA256($0.baseAddress, CC_LONG(data.count), &digest) }
    return digest.map { String(format: "%02x", $0) }.joined()
}

// MARK: - Helpers

// Drain a pipe read-fd into a Data buffer, capped at `max` bytes.
// Reads until EOF (write end closed) or cap reached. Closes the fd when done.
private func wasmDrainPipe(_ fd: Int32, max: Int) -> Data {
    var data = Data()
    var buf  = [UInt8](repeating: 0, count: 4096)
    while data.count < max {
        let n = read(fd, &buf, min(buf.count, max - data.count))
        if n <= 0 { break }
        data.append(contentsOf: buf[..<n])
    }
    close(fd)
    return data
}

// MARK: - NSLock compatibility (withLock added in Swift 5.7 / iOS 16)

private extension NSLock {
    @discardableResult
    func withLock<T>(_ body: () throws -> T) rethrows -> T {
        lock()
        defer { unlock() }
        return try body()
    }
}

// MARK: - Errors

private enum SandboxError: LocalizedError {
    case invalidURL
    case downloadFailed(Int)
    case sha256Mismatch(expected: String, got: String)

    var errorDescription: String? {
        switch self {
        case .invalidURL:
            return "Invalid Wasm download URL."
        case .downloadFailed(let code):
            return "Failed to download Alpine Wasm image (HTTP \(code))."
        case .sha256Mismatch(let expected, let got):
            return "Wasm image SHA256 mismatch. Expected \(expected), got \(got)."
        }
    }
}
